name: scout-audit
on:
  pull_request:
    branches:
      - master

jobs:
  scout-audit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      repository-projects: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: do scout
        uses: coinfabrik/scout-actions@v3
        with:
          target: "./pallets/ethereum-checked"

      - uses: mshick/add-pr-comment@v2.8.2
        with:
          message-path: ${{ github.workspace }}/report.md
